config/routes.rb
Rails.application.routes.draw do

  resources :pcategories

  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  get 'welcome/home'
  root 'welcome#home'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,   :validate => true
	attribute :nickname,  :captcha  => true

	def headers
  	{
	  	:subject => "Contact Form",
	  	:to => "mailtoarslan.pak@gmail.com",
	  	:from => %("#{name}" <#{email}>)
	  }
	end

end

app/models/pcategory.rb
class Pcategory < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged 


	has_many :posts
	validates :name, presence: true, uniqueness: :true
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged 
	validates :title, presence: true
	validates :pcategory_id, presence: true
	validates :content, presence: true
	belongs_to :pcategory
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end
	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send Message'
			render :new
		end
	end
end

app/controllers/pcategories_controller.rb
class PcategoriesController < ApplicationController
  before_action :find_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def new
    @pcategory = Pcategory.new
  end

  def create
    @pcategory = Pcategory.new pcategory_params
    if @pcategory.save
      redirect_to root_path, notice: "Article saved!"
    else
      render 'new', notice: "Unable to save post"
    end
  end

  def index
    @pcategories = Pcategory.all 
  end
  def show

  end
  def edit
  end
  def update
    if @pcategoryt.update pcategory_params
      redirect_to @pcategory, notice: 'Updated'
    else
      render 'edit', notice: 'Error!'
    end
  end

  def destroy
    if @pcategory.destroy
      redirect_to pcategories_path, notice: 'Deleted'
    else
      redirect_to @pcategory, notice: 'Error to deleted'
    end
  end
  private
  def pcategory_params
    params.require(:pcategory).permit(:name, :slug)
  end
  def find_category
    @pcategory = Pcategory.friendly.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 2)
	end
	def new
		@post = Post.new
	end
	def create
		@post = Post.new post_params
		if @post.save
			redirect_to @post, notice: "Article saved!"
		else
			render 'new', notice: "Unable to save post"
		end
	end
	def show

	end

	def edit
	end
	def update
		if @post.update post_params
			redirect_to @post, notice: 'Updated'
		else
			render 'edit', notice: 'Error!'
		end
	end
	def destroy
		if @post.destroy
			redirect_to posts_path, notice: 'Deleted'
		else
			redirect_to @post, notice: 'Error to deleted'
		end
	end
	private

	def post_params
		params.require(:post).permit(:title, :content, :pcategory_id, :slug)
	end
	def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@projects = Project.all.order("created_at desc")
		
	end
	def new
		@project = Project.new
	end
	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "Project Saved"
		else
			render 'new', notice: 'Error Project could not be saved. Try again!'
		end
	end
	def show
	end

	def edit
	end
	def update
		if @project.update project_params
			redirect_to @project, notice: 'Updated'
		else
			render 'edit', notice: 'Error!'
		end
	end
	def destroy
		if @project.destroy
			redirect_to projects_path, notice: 'Deleted'
		else
			redirect_to @project, notice: 'Error to deleted'
		end
	end

	private

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)
	end
	def find_project
		@project = Project.friendly.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
		@projects = Project.all.limit(3).order("created_at desc")
	end
	def home


	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
	    def block_code(code, language)
	      Pygments.highlight(code, lexer: language)
	    end
  	end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pcategories_helper.rb
module PcategoriesHelper
end

app/helpers/pcategory_helper.rb
module PcategoryHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">SAY HI!</h1>
<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for contacting us.</h1>
	<p> We will back to you soon</p>
</div>

app/views/contacts/new.html.erb
<!-- Put this code anywhere in the body of your page where you want the badge to show up. -->
<div align="center" style="margin-top: 40px;">
<div itemscope itemtype='http://schema.org/Person' class='fiverr-seller-widget' style='display: inline-block;'>
     <a itemprop='url' href=https://www.fiverr.com/arsalan_23 rel="nofollow" target="_blank" style='display: inline-block;'>
        <div class='fiverr-seller-content' id='fiverr-seller-widget-content-f2882e6b-83c1-40a9-85b0-80d3df0d2825' itemprop='contentURL' style='display: none;'></div>
        <div id='fiverr-widget-seller-data' style='display: none;'>
            <div itemprop='name' >arsalan_23</div>
            <div itemscope itemtype='http://schema.org/Organization'><span itemprop='name'>Fiverr</span></div>
            <div itemprop='jobtitle'>Seller</div>
            <div itemprop='description'>I have been providing Commercial Web Solutions using Rails for 2+ yrs.I am specialize in building websites using Test Driven Approach and modern tools having experience in Ruby, RubyOnRails,Version control with Git,Cloud server Heroku,Expert In BDD and TDD, Sqlite3,Mysql.HTML,Twitter bootstrap

</div>
        </div>
    </a>
</div>
</div>

<script id='fiverr-seller-widget-script-f2882e6b-83c1-40a9-85b0-80d3df0d2825' src='https://widgets.fiverr.com/api/v1/seller/arsalan_23?widget_id=f2882e6b-83c1-40a9-85b0-80d3df0d2825' data-config='{"category_name":"Programming & Tech"}' async='true' defer='true'></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZAT | Developers</title>
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if params[:controller] != 'welcome' %>
	<header id="main-navigation" class="clearfix">
		<%= link_to (image_tag 'zat-web.png'), root_path, class: 'name' %>
	<nav>
		<b><%= link_to 'Articles', posts_path %></b>
		<% if params[:controller] == 'posts' %><b><%= link_to 'Categories', pcategories_path %></b><%end %>
		<b><%=link_to "Projects", projects_path %></b>
		<b><%= link_to "Contact", new_contact_path %></b>
		<% if user_signed_in? %>
			<b><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
		<% end %>
	</nav>
	</header>
	<% end %>
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% elsif alert %>
	    <p class="alert"><%= alert %></p>
	<% end %>

	<%= yield %>
	<% if params[:controller] != 'welcome' %>
	<footer id="main_footer">
		<p class="copyright"> &copy;2016  ZAT.PK | SOFTWARE ENGINEERS</p>
		<nav>
			<a href="#"><i class="fa fa-lg fa-twitter"></i></a>
			<a href="#"><i class="fa fa-lg fa-github"></i></a>
			<a href="#"><i class="fa fa-lg fa-youtube" aria-hidden="true"></i></i></a>
		</nav>
	</footer>
	<% end %>

</body>
</html>

app/views/pcategories/_form.html.erb
<%= form_for @pcategory do |f| %>
	

	<%= f.label :name %><br>
	<%= f.text_field :name %>

	<br>
	<br>
	<%= f.submit %>
<% end %>

app/views/pcategories/edit.html.erb
<h1 id="page_title">Edit Category</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/pcategories/index.html.erb
<h1 id="page_title">All Categories   <% if user_signed_in? %>  [<small><i><%= link_to "Add Category", new_pcategory_path, style: "text-decoration:none" %></i></small>] <% end %></h1> 
<div id="posts_wrapper" class="skinny_wrapper">
	<% @pcategories.each do |post| %>
		<div class="post">
			<p class="date"><%= post.posts.count%> posts</p>
			<h2><a href="#"><%= link_to post.name, post %></a></h2>
			<hr>
		</div>
	<% end %>
</div>

app/views/pcategories/new.html.erb
<h1 id="page_title">New Category</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/pcategories/show.html.erb
<h1 id="page_title"><%= @pcategory.name%>'s Articles</h1> | 
<div id="posts_wrapper" class="skinny_wrapper">
	<% @pcategory.posts.each do |post| %>
		<div class="post">
			<p class="date"><%= post.created_at.strftime('%A, %B %d')%></p>
			<h2><a href="#"><%= link_to post.title, post %></a></h2>
			<hr>
		</div>
	<% end %>
</div>

<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to 'Edit', edit_pcategory_path(@pcategory) %>
			<%= link_to 'Delete', pcategory_path(@pcategory), method: :delete, data: {confirm: "Are you sure"} %>
		</div>
	<% end %>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
var disqus_shortname = "ZAT";
var disqus_identifier = '<%= @post.id %>';
var disqus_title = '<%= @post.title%>';
var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';


/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//zat.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from being saved</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :pcategory, 'Select Category' %>
	<%= f.select :pcategory_id, Pcategory.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class: 'select' %>

	<br>
	<br>

	<%= f.label :content, "Write Your article Here" %><br>
	<%= f.text_area :content %>

	
	<br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Article</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff i've written</h1>
<div id="posts_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
		<div class="post">
			<p class="date"><%= post.created_at.strftime('%A, %B %d')%></p>
			<h2><a href="#"><%= link_to post.title, post %></a></h2>
			<hr>
		</div>
	<% end %>
</div>
<div align="center">
	<%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1 id="page_title">New Article</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime("%A, %b %d ") %></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>
	<div id="content">
		<%= markdown @post.content %>
	</div>
	
	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to 'Edit', edit_post_path(@post) %>
			<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure"} %>
		</div>
	<% end %>

	<hr>
	<div id="share_box">
		<p> Share: <%= @post.title %></p>
		<!-- Twitter -->
		<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @Engr_Arslan007 - &amp;url=<%= url_for([@post, {only_path: false}]) %>','_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-lg fa-twitter"></i></a>
		<a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-lg fa-facebook"></i></a>
	    <!-- Google Plus -->
	    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-lg fa-google-plus"></i></a>
	</div>
	<hr>
	<%= render 'disqus' %>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error") %> prevemnted this post from being saved %>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :description, "Write Your Description Here" %><br>
	<%= f.text_area :description %>

	<br>
	<br>
	<%= f.label :link %><br>
	<%= f.text_field :link %>

	<br>
	<br>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Edit Project</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff i've built</h1>
<div id="posts_wrapper" class="skinny_wrapper">
	<% @projects.each do |project| %>
		<div class="post">
			<p class="date"><%= project.created_at.strftime('%A, %B %d')%></p>
			<h2><a href="#"><%= link_to project.title, project %></a></h2>
			<hr>
		</div>
	<% end %>
</div>

app/views/projects/new.html.erb
<h1 id="page_title">New Project</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime("%A, %b %d ") %></p>
		<h1><%= @project.title %></h1>
		<hr>
	</header>
	<div id="content">
		<%= markdown @project.description %>
		<div class="button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank">Visit: <%= @project.title %></a>
		</div>
	</div>
	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to 'New', new_project_path %>
			<%= link_to 'Edit', edit_project_path(@project) %>
			<%= link_to 'Delete', project_path(@project), method: :delete, data:{confirm: "Are you sure?"} %>
		</div>
	<% end %>
	<hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>About Us</h2>
		<hr>
		<p>We are a team of Developers &amp; Designers.We are a team of Developers and Designers.</p>
		<p>We are a team of Developers and Designers.</p>
		<p>We are a team of Developers and
		Designers.We are a team of Developers and Designers.</p>
		<p>We are a team of Developers and
		.</p>
		 <p>We are a team of Developers and <a href="#"> Designers</a>.</p>
	</div>
	<div class="col-2 homepage_content">
		<h2><a href="#">Blog Posts</a></h2>
		<hr>
		<% @posts.each do |post| %>
			<h3><%= link_to post.title, post %> </h3>
			<p class="date"><%= post.created_at.strftime("%A, %b %d ") %></p>
		<% end %>
		
	</div>
	<div class="col-3  homepage_content">
		<h1><a href="#">Projects</a></h1>
		<hr>
		<% @projects.each do |project| %>
			<h3><%= link_to project.title, project %> </h3>
			<p class="date"><%= project.created_at.strftime("%A, %b %d ") %></p>
		<% end %>
	</div>
</div>